site_name: Manual Catálogo de Inventário do Governo Federal
theme: readthedocs
repo_url: https://github.com/govbr/catalogo-govbr/
site_description: Manual do Catálogo de Inventário do Governo Federal Brasileiro.
copyright: CC0
repo_name: <i class="fa fa-github"></i> Contribua com o Manual
site_author: Ministério do Planejamento, Orçamento e Desenvolvimento
extra:
  siorg: http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/2981

pages:
- Início: 'index.md'
- Inventário:
    - 'Catalogando Inventário de bases de dados': 'catalogando/inventario.md'
    - 'Adicionar dados': 'catalogando/adicionar-dados.md'

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - smarty

